blank_issues_enabled: false
contact_links:
    - name: ğŸ’¡ Suggest a new feature or discuss one
      url:  https://github.com/minimailboxes/all-in-one/discussions/categories/ideas
      about: For new feature requests and discussion of existing ones
    - name: â“ Questions on AIO
      url: https://github.com/minimailboxes/all-in-one/discussions/categories/questions
      about: For questions regarding AIO
    - name: â›‘ï¸ Community Support and Help
      url: https://help.minimailboxes.com/tag/aio
      about: For other types of questions
    - name: ğŸ’¼ MiniMailboxes Enterprise
      url: https://portal.minimailboxes.com/
      about: If you are a MiniMailboxes Enterprise customer, or need Professional support, so it can be resolved directly by our dedicated engineers more quickly